name: Tests

on: 
  - pull_request

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: 7.4
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, mysql, intl, gd, exif, iconv, imagick
        coverage: pcov
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run tests
      run: php -d pcov.enabled=1 -d memory_limit=4G vendor/phpunit/phpunit/phpunit --coverage-clover=build/logs/clover.xml tests
      
    - name: CodeCov
      run: curl -Os https://uploader.codecov.io/latest/linux/codecov ; chmod +x codecov ; ./codecov

    - name: Coverage Upload
      run: export REPO_TOKEN="2798b334-9efc-4f8b-97ba-13a5534af4c3" && curl -Ls https://raw.githubusercontent.com/getOtterWise/bash-uploader/main/uploader.sh | bash -s -- --endpoint http://2683jrahzu.laravel-sail.site:8080/ingress/upload --verbose true --ignore-errors true
