name: PHP Composer

on: pull_request

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: 7.4
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, mysql, intl, gd, exif, iconv, imagick
        coverage: pcov
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run tests
      run: php -d pcov.enabled=1 -d memory_limit=4G vendor/phpunit/phpunit/phpunit --coverage-clover=build/logs/clover.xml tests
      
    - uses: mdecoleman/pr-branch-name@1.2.0
      id: vars
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Upload Coverage to Cotter
      run: curl -F clover=@build/logs/clover.xml -F github_token=${{ secrets.GITHUB_TOKEN }} -F github_repo=${{ github.repository }} -F github_commit=${{ github.sha }} -F github_ref=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH") -F github_branch=${{ steps.vars.outputs.branch }} -F github_head_commit=${{github.event.pull_request.head.sha}} -F github_head_branch=${{github.event.pull_request.base.ref}} -F dir="/home/runner/work/" http://lu9yqrd2y2.laravel-sail.site:8080/ingress/upload
